name: Deploy to Azure

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # 1. Connexion au registre Docker (ACR) pour pouvoir Pousser l'image
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    # 2. Construction et Envoi de l'image
    - run: |
        docker build . -t ${{ secrets.ACR_LOGIN_SERVER }}/monapp:latest
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/monapp:latest
        
    # 3. DÃ©ploiement sur la Web App via le Profil de Publication (La correction est ICI)
    - name: Deploy via Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'projetazure-webapp'
        # On passe SEULEMENT le nom de l'image (monapp:latest)
        images: 'monapp:latest' 
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}